let test = 15;
let a = test.toString();
let b = test.toString(2);
let c = test.toString(8);
let d = test.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test2 = 15.16698;
a = test2.toString();
b = test2.toString(2);
c = test2.toString(8);
d = test2.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test3 = 7.78714;
a = test3.toString();
b = test3.toString(2);
c = test3.toString(8);
d = test3.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test4 = Number("12.3");
a = test4.toString();
b = test4.toString(2);
c = test4.toString(8);
d = test4.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test5 = Number("3.14random");
a = test5.toString();
b = test5.toString(2);
c = test5.toString(8);
d = test5.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test7 = Number(true);
a = test7.toString();
b = test7.toString(2);
c = test7.toString(8);
d = test7.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test8 = Number(false);
a = test8.toString();
b = test8.toString(2);
c = test8.toString(8);
d = test8.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test9 = Number("321");
a = test9.toString();
b = test9.toString(2);
c = test9.toString(8);
d = test9.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);
let test10 = Number("Supercode");
a = test10.toString();
b = test10.toString(2);
c = test10.toString(8);
d = test10.toString(16);
console.log(a);
console.log(b);
console.log(c);
console.log(d);



